from flask import Flask, request, jsonify, send_from_directory
from flask_cors import CORS
import os
import asyncio
import time
from dotenv import load_dotenv
from gemini_service import GeminiService
from elevenlabs_service import ElevenLabsService

# Load environment variables
load_dotenv()

app = Flask(__name__)
CORS(app)  # Enable CORS for frontend communication

# Initialize services
gemini_service = None
elevenlabs_service = None

def initialize_services():
    """Initialize AI services with API keys"""
    global gemini_service, elevenlabs_service
    
    try:
        # Initialize Gemini service
        gemini_api_key = os.getenv('GEMINI_API_KEY')
        if not gemini_api_key:
            raise ValueError("GEMINI_API_KEY not found in environment variables")
        
        gemini_service = GeminiService(gemini_api_key)
        
        # Clean up any existing sessions on startup
        gemini_service.cleanup_expired_sessions()
        
        # Initialize ElevenLabs service
        elevenlabs_api_key = os.getenv('ELEVENLABS_API_KEY')
        elevenlabs_voice_id = os.getenv('ELEVENLABS_VOICE_ID')
        
        if not elevenlabs_api_key:
            raise ValueError("ELEVENLABS_API_KEY not found in environment variables")
        
        elevenlabs_service = ElevenLabsService(elevenlabs_api_key, elevenlabs_voice_id)
        
        print("✅ All services initialized successfully")
        
    except Exception as e:
        print(f"❌ Error initializing services: {e}")
        raise e

@app.route('/api/chat', methods=['POST'])
def chat():
    """
    Main chat endpoint that handles:
    1. User message → Gemini → Text response
    2. Text response → ElevenLabs → Audio file
    3. Return text + audio URL to frontend
    """
    start_time = time.time()
    
    try:
        data = request.get_json()
        user_message = data.get('message', '')
        session_id = data.get('session_id', 'default_session')
        language = data.get('language', 'georgian')  # Default to Georgian
        
        if not user_message:
            return jsonify({'error': 'No message provided'}), 400
        
        print(f"🤖 Processing message for session {session_id} in {language}: {user_message[:50]}...")
        print(f"🆔 Session ID: {session_id}")
        
        # Run async functions in event loop
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        
        try:
            # Get or create session
            session = gemini_service.get_or_create_session(session_id)
            
            # Step 1: Generate AI response with Gemini (using session context and language)
            print("📝 Generating AI response...")
            ai_response = loop.run_until_complete(gemini_service.generate_tech_support_response(user_message, session, language))
            print(f"✅ AI Response: {ai_response}")
            
            # Add the exchange to session history
            session.add_message(user_message, ai_response)
            
            # Check if session should be saved (conversation ended)
            if gemini_service.should_save_session(user_message, ai_response):
                print(f"💾 Conversation ended, saving session {session_id}...")
                gemini_service.save_session_to_file(session, language)
            
            # Step 2: Generate audio with ElevenLabs (using language-specific model)
            print("🎵 Generating audio...")
            audio_url = loop.run_until_complete(elevenlabs_service.generate_audio(ai_response, language))
            print(f"✅ Audio generated: {audio_url}")
            
        finally:
            loop.close()
        
        # Calculate total response time
        total_time = (time.time() - start_time) * 1000
        print(f"⏱️ Total response time: {total_time:.3f}ms")
        
        # Return response to frontend
        return jsonify({
            'text': ai_response,
            'audioUrl': audio_url,
            'visemes': [],  # Will be generated by frontend using wawa-lipsync
            'session_id': session_id
        })
        
    except Exception as e:
        print(f"❌ Error in chat endpoint: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/static/audio/<filename>')
def serve_audio(filename):
    """Serve audio files to frontend"""
    return send_from_directory('static/audio', filename)

@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint"""
    return jsonify({'status': 'healthy'})

@app.route('/api/cleanup', methods=['POST'])
def cleanup_sessions():
    """Clean up expired sessions"""
    try:
        gemini_service.cleanup_expired_sessions()
        return jsonify({'status': 'sessions cleaned up'})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/save-session/<session_id>', methods=['POST'])
def save_session(session_id):
    """Manually save a specific session to file"""
    try:
        if session_id not in gemini_service.user_sessions:
            return jsonify({'error': 'Session not found'}), 404
        
        session = gemini_service.user_sessions[session_id]
        filepath = gemini_service.save_session_to_file(session, session.language if hasattr(session, 'language') else 'georgian')
        
        if filepath:
            return jsonify({'status': 'session saved', 'filepath': filepath})
        else:
            return jsonify({'error': 'Failed to save session'}), 500
            
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    # Initialize services on startup
    try:
        initialize_services()
    except Exception as e:
        print(f"Failed to initialize services: {e}")
        exit(1)
    
    port = int(os.environ.get('PORT', 3001))
    print(f"🚀 Starting server on http://localhost:{port}")
    app.run(host='0.0.0.0', port=port, debug=True)
